# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created: Sun Oct  3 15:54:38 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelPath = QtGui.QLabel(self.centralwidget)
        self.labelPath.setObjectName("labelPath")
        self.gridLayout.addWidget(self.labelPath, 0, 0, 1, 1)
        self.lineEditPath = QtGui.QLineEdit(self.centralwidget)
        self.lineEditPath.setObjectName("lineEditPath")
        self.gridLayout.addWidget(self.lineEditPath, 0, 1, 1, 1)
        self.pushButtonBrowse = QtGui.QPushButton(self.centralwidget)
        self.pushButtonBrowse.setObjectName("pushButtonBrowse")
        self.gridLayout.addWidget(self.pushButtonBrowse, 0, 2, 1, 1)
        self.labelFormat = QtGui.QLabel(self.centralwidget)
        self.labelFormat.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.labelFormat.setObjectName("labelFormat")
        self.gridLayout.addWidget(self.labelFormat, 1, 0, 1, 1)
        self.lineEditFormat = QtGui.QLineEdit(self.centralwidget)
        self.lineEditFormat.setReadOnly(True)
        self.lineEditFormat.setObjectName("lineEditFormat")
        self.gridLayout.addWidget(self.lineEditFormat, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBoxSign = QtGui.QComboBox(self.centralwidget)
        self.comboBoxSign.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBoxSign.setObjectName("comboBoxSign")
        self.comboBoxSign.addItem("")
        self.comboBoxSign.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxSign)
        self.spinBoxM = QtGui.QSpinBox(self.centralwidget)
        self.spinBoxM.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxM.setMaximum(59)
        self.spinBoxM.setObjectName("spinBoxM")
        self.horizontalLayout_2.addWidget(self.spinBoxM)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBoxS = QtGui.QSpinBox(self.centralwidget)
        self.spinBoxS.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxS.setMaximum(59)
        self.spinBoxS.setObjectName("spinBoxS")
        self.horizontalLayout_2.addWidget(self.spinBoxS)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.spinBoxMS = QtGui.QSpinBox(self.centralwidget)
        self.spinBoxMS.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxMS.setMaximum(999)
        self.spinBoxMS.setObjectName("spinBoxMS")
        self.horizontalLayout_2.addWidget(self.spinBoxMS)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.pushButtonLaunch = QtGui.QPushButton(self.centralwidget)
        self.pushButtonLaunch.setObjectName("pushButtonLaunch")
        self.gridLayout_2.addWidget(self.pushButtonLaunch, 1, 0, 1, 1)
        self.textEditResult = QtGui.QPlainTextEdit(self.centralwidget)
        self.textEditResult.setObjectName("textEditResult")
        self.gridLayout_2.addWidget(self.textEditResult, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonCopy = QtGui.QPushButton(self.centralwidget)
        self.pushButtonCopy.setObjectName("pushButtonCopy")
        self.horizontalLayout.addWidget(self.pushButtonCopy)
        self.pushButtonOverwrite = QtGui.QPushButton(self.centralwidget)
        self.pushButtonOverwrite.setObjectName("pushButtonOverwrite")
        self.horizontalLayout.addWidget(self.pushButtonOverwrite)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "DecalST", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPath.setText(QtGui.QApplication.translate("MainWindow", "Chemin", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonBrowse.setText(QtGui.QApplication.translate("MainWindow", "Parcourir ...", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFormat.setText(QtGui.QApplication.translate("MainWindow", "Format", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Décallage", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSign.setItemText(0, QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSign.setItemText(1, QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "ms", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonLaunch.setText(QtGui.QApplication.translate("MainWindow", "Lancer !", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCopy.setText(QtGui.QApplication.translate("MainWindow", "Tout copier", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOverwrite.setToolTip(QtGui.QApplication.translate("MainWindow", "Cette action écrasera le fichier original par ce contenu", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOverwrite.setText(QtGui.QApplication.translate("MainWindow", "Écraser le fichier par ce contenu", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

