# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created: Tue Jun 14 20:54:59 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelFormat = QtGui.QLabel(self.centralwidget)
        self.labelFormat.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.labelFormat.setObjectName("labelFormat")
        self.horizontalLayout_3.addWidget(self.labelFormat)
        self.lineEditFormat = QtGui.QLineEdit(self.centralwidget)
        self.lineEditFormat.setReadOnly(True)
        self.lineEditFormat.setObjectName("lineEditFormat")
        self.horizontalLayout_3.addWidget(self.lineEditFormat)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.tabs = QtGui.QTabWidget(self.centralwidget)
        self.tabs.setTabPosition(QtGui.QTabWidget.West)
        self.tabs.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabs.setObjectName("tabs")
        self.tabShift = QtGui.QWidget()
        self.tabShift.setObjectName("tabShift")
        self.verticalLayout = QtGui.QVBoxLayout(self.tabShift)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelPath = QtGui.QLabel(self.tabShift)
        self.labelPath.setObjectName("labelPath")
        self.horizontalLayout_4.addWidget(self.labelPath)
        self.lineEditPathShiftIn = QtGui.QLineEdit(self.tabShift)
        self.lineEditPathShiftIn.setObjectName("lineEditPathShiftIn")
        self.horizontalLayout_4.addWidget(self.lineEditPathShiftIn)
        self.pushButtonBrowseShiftIn = QtGui.QPushButton(self.tabShift)
        self.pushButtonBrowseShiftIn.setObjectName("pushButtonBrowseShiftIn")
        self.horizontalLayout_4.addWidget(self.pushButtonBrowseShiftIn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.radioButtonShift = QtGui.QRadioButton(self.tabShift)
        self.radioButtonShift.setChecked(True)
        self.radioButtonShift.setObjectName("radioButtonShift")
        self.horizontalLayout_13.addWidget(self.radioButtonShift)
        self.radioButtonBeginAt = QtGui.QRadioButton(self.tabShift)
        self.radioButtonBeginAt.setObjectName("radioButtonBeginAt")
        self.horizontalLayout_13.addWidget(self.radioButtonBeginAt)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBoxSignShift = QtGui.QComboBox(self.tabShift)
        self.comboBoxSignShift.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBoxSignShift.setObjectName("comboBoxSignShift")
        self.comboBoxSignShift.addItem("")
        self.comboBoxSignShift.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxSignShift)
        self.spinBoxShiftH = QtGui.QSpinBox(self.tabShift)
        self.spinBoxShiftH.setObjectName("spinBoxShiftH")
        self.horizontalLayout_2.addWidget(self.spinBoxShiftH)
        self.label_5 = QtGui.QLabel(self.tabShift)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.spinBoxShiftM = QtGui.QSpinBox(self.tabShift)
        self.spinBoxShiftM.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxShiftM.setMaximum(59)
        self.spinBoxShiftM.setObjectName("spinBoxShiftM")
        self.horizontalLayout_2.addWidget(self.spinBoxShiftM)
        self.label_2 = QtGui.QLabel(self.tabShift)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBoxShiftS = QtGui.QSpinBox(self.tabShift)
        self.spinBoxShiftS.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxShiftS.setMaximum(59)
        self.spinBoxShiftS.setObjectName("spinBoxShiftS")
        self.horizontalLayout_2.addWidget(self.spinBoxShiftS)
        self.label_3 = QtGui.QLabel(self.tabShift)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.spinBoxShiftMS = QtGui.QSpinBox(self.tabShift)
        self.spinBoxShiftMS.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxShiftMS.setMaximum(999)
        self.spinBoxShiftMS.setObjectName("spinBoxShiftMS")
        self.horizontalLayout_2.addWidget(self.spinBoxShiftMS)
        self.label_4 = QtGui.QLabel(self.tabShift)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.textEditShiftOut = QtGui.QPlainTextEdit(self.tabShift)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEditShiftOut.setFont(font)
        self.textEditShiftOut.setObjectName("textEditShiftOut")
        self.verticalLayout.addWidget(self.textEditShiftOut)
        self.tabs.addTab(self.tabShift, "")
        self.tabConcat = QtGui.QWidget()
        self.tabConcat.setObjectName("tabConcat")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabConcat)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.labelPath_2 = QtGui.QLabel(self.tabConcat)
        self.labelPath_2.setObjectName("labelPath_2")
        self.horizontalLayout_11.addWidget(self.labelPath_2)
        self.lineEditPathConcatIn1 = QtGui.QLineEdit(self.tabConcat)
        self.lineEditPathConcatIn1.setObjectName("lineEditPathConcatIn1")
        self.horizontalLayout_11.addWidget(self.lineEditPathConcatIn1)
        self.pushButtonBrowseConcatIn1 = QtGui.QPushButton(self.tabConcat)
        self.pushButtonBrowseConcatIn1.setObjectName("pushButtonBrowseConcatIn1")
        self.horizontalLayout_11.addWidget(self.pushButtonBrowseConcatIn1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelPath_7 = QtGui.QLabel(self.tabConcat)
        self.labelPath_7.setObjectName("labelPath_7")
        self.horizontalLayout_7.addWidget(self.labelPath_7)
        self.lineEditPathConcatIn2 = QtGui.QLineEdit(self.tabConcat)
        self.lineEditPathConcatIn2.setObjectName("lineEditPathConcatIn2")
        self.horizontalLayout_7.addWidget(self.lineEditPathConcatIn2)
        self.pushButtonBrowseConcatIn2 = QtGui.QPushButton(self.tabConcat)
        self.pushButtonBrowseConcatIn2.setObjectName("pushButtonBrowseConcatIn2")
        self.horizontalLayout_7.addWidget(self.pushButtonBrowseConcatIn2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelPath_3 = QtGui.QLabel(self.tabConcat)
        self.labelPath_3.setObjectName("labelPath_3")
        self.horizontalLayout_6.addWidget(self.labelPath_3)
        self.lineEditPathConcatOut = QtGui.QLineEdit(self.tabConcat)
        self.lineEditPathConcatOut.setObjectName("lineEditPathConcatOut")
        self.horizontalLayout_6.addWidget(self.lineEditPathConcatOut)
        self.pushButtonBrowseConcatOut = QtGui.QPushButton(self.tabConcat)
        self.pushButtonBrowseConcatOut.setObjectName("pushButtonBrowseConcatOut")
        self.horizontalLayout_6.addWidget(self.pushButtonBrowseConcatOut)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.comboBoxSignConcat = QtGui.QComboBox(self.tabConcat)
        self.comboBoxSignConcat.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBoxSignConcat.setObjectName("comboBoxSignConcat")
        self.comboBoxSignConcat.addItem("")
        self.comboBoxSignConcat.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBoxSignConcat)
        self.spinBoxConcatH = QtGui.QSpinBox(self.tabConcat)
        self.spinBoxConcatH.setObjectName("spinBoxConcatH")
        self.horizontalLayout_5.addWidget(self.spinBoxConcatH)
        self.label_6 = QtGui.QLabel(self.tabConcat)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.spinBoxConcatM = QtGui.QSpinBox(self.tabConcat)
        self.spinBoxConcatM.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxConcatM.setMaximum(59)
        self.spinBoxConcatM.setObjectName("spinBoxConcatM")
        self.horizontalLayout_5.addWidget(self.spinBoxConcatM)
        self.label_7 = QtGui.QLabel(self.tabConcat)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.spinBoxConcatS = QtGui.QSpinBox(self.tabConcat)
        self.spinBoxConcatS.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxConcatS.setMaximum(59)
        self.spinBoxConcatS.setObjectName("spinBoxConcatS")
        self.horizontalLayout_5.addWidget(self.spinBoxConcatS)
        self.label_8 = QtGui.QLabel(self.tabConcat)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.spinBoxConcatMS = QtGui.QSpinBox(self.tabConcat)
        self.spinBoxConcatMS.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxConcatMS.setMaximum(999)
        self.spinBoxConcatMS.setObjectName("spinBoxConcatMS")
        self.horizontalLayout_5.addWidget(self.spinBoxConcatMS)
        self.label_9 = QtGui.QLabel(self.tabConcat)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.splitter = QtGui.QSplitter(self.tabConcat)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget_6 = QtGui.QWidget(self.splitter)
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_13 = QtGui.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_8.addWidget(self.label_13)
        self.textEditConcatIn1 = QtGui.QPlainTextEdit(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEditConcatIn1.setFont(font)
        self.textEditConcatIn1.setObjectName("textEditConcatIn1")
        self.verticalLayout_8.addWidget(self.textEditConcatIn1)
        self.layoutWidget_7 = QtGui.QWidget(self.splitter)
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_14 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_9.addWidget(self.label_14)
        self.textEditConcatIn2 = QtGui.QPlainTextEdit(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEditConcatIn2.setFont(font)
        self.textEditConcatIn2.setObjectName("textEditConcatIn2")
        self.verticalLayout_9.addWidget(self.textEditConcatIn2)
        self.layoutWidget_5 = QtGui.QWidget(self.splitter)
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_12 = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_7.addWidget(self.label_12)
        self.textEditConcatOut = QtGui.QPlainTextEdit(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEditConcatOut.setFont(font)
        self.textEditConcatOut.setObjectName("textEditConcatOut")
        self.verticalLayout_7.addWidget(self.textEditConcatOut)
        self.verticalLayout_2.addWidget(self.splitter)
        self.tabs.addTab(self.tabConcat, "")
        self.tabSplit = QtGui.QWidget()
        self.tabSplit.setObjectName("tabSplit")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tabSplit)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelPath_6 = QtGui.QLabel(self.tabSplit)
        self.labelPath_6.setObjectName("labelPath_6")
        self.horizontalLayout_8.addWidget(self.labelPath_6)
        self.lineEditPathSplitIn = QtGui.QLineEdit(self.tabSplit)
        self.lineEditPathSplitIn.setObjectName("lineEditPathSplitIn")
        self.horizontalLayout_8.addWidget(self.lineEditPathSplitIn)
        self.pushButtonBrowseSplitIn = QtGui.QPushButton(self.tabSplit)
        self.pushButtonBrowseSplitIn.setObjectName("pushButtonBrowseSplitIn")
        self.horizontalLayout_8.addWidget(self.pushButtonBrowseSplitIn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.labelPath_5 = QtGui.QLabel(self.tabSplit)
        self.labelPath_5.setObjectName("labelPath_5")
        self.horizontalLayout_9.addWidget(self.labelPath_5)
        self.lineEditPathSplitOut1 = QtGui.QLineEdit(self.tabSplit)
        self.lineEditPathSplitOut1.setObjectName("lineEditPathSplitOut1")
        self.horizontalLayout_9.addWidget(self.lineEditPathSplitOut1)
        self.pushButtonBrowseSplitOut1 = QtGui.QPushButton(self.tabSplit)
        self.pushButtonBrowseSplitOut1.setObjectName("pushButtonBrowseSplitOut1")
        self.horizontalLayout_9.addWidget(self.pushButtonBrowseSplitOut1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.labelPath_4 = QtGui.QLabel(self.tabSplit)
        self.labelPath_4.setObjectName("labelPath_4")
        self.horizontalLayout_10.addWidget(self.labelPath_4)
        self.lineEditPathSplitOut2 = QtGui.QLineEdit(self.tabSplit)
        self.lineEditPathSplitOut2.setObjectName("lineEditPathSplitOut2")
        self.horizontalLayout_10.addWidget(self.lineEditPathSplitOut2)
        self.pushButtonBrowseSplitOut2 = QtGui.QPushButton(self.tabSplit)
        self.pushButtonBrowseSplitOut2.setObjectName("pushButtonBrowseSplitOut2")
        self.horizontalLayout_10.addWidget(self.pushButtonBrowseSplitOut2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_19 = QtGui.QLabel(self.tabSplit)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_12.addWidget(self.label_19)
        self.spinBoxSplitH = QtGui.QSpinBox(self.tabSplit)
        self.spinBoxSplitH.setObjectName("spinBoxSplitH")
        self.horizontalLayout_12.addWidget(self.spinBoxSplitH)
        self.label_15 = QtGui.QLabel(self.tabSplit)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_12.addWidget(self.label_15)
        self.spinBoxSplitM = QtGui.QSpinBox(self.tabSplit)
        self.spinBoxSplitM.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxSplitM.setMaximum(59)
        self.spinBoxSplitM.setObjectName("spinBoxSplitM")
        self.horizontalLayout_12.addWidget(self.spinBoxSplitM)
        self.label_16 = QtGui.QLabel(self.tabSplit)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_12.addWidget(self.label_16)
        self.spinBoxSplitS = QtGui.QSpinBox(self.tabSplit)
        self.spinBoxSplitS.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxSplitS.setMaximum(59)
        self.spinBoxSplitS.setObjectName("spinBoxSplitS")
        self.horizontalLayout_12.addWidget(self.spinBoxSplitS)
        self.label_17 = QtGui.QLabel(self.tabSplit)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_12.addWidget(self.label_17)
        self.spinBoxSplitMS = QtGui.QSpinBox(self.tabSplit)
        self.spinBoxSplitMS.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxSplitMS.setMaximum(999)
        self.spinBoxSplitMS.setObjectName("spinBoxSplitMS")
        self.horizontalLayout_12.addWidget(self.spinBoxSplitMS)
        self.label_18 = QtGui.QLabel(self.tabSplit)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_12.addWidget(self.label_18)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.splitter_2 = QtGui.QSplitter(self.tabSplit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget_9 = QtGui.QWidget(self.splitter_2)
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_9)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtGui.QLabel(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.textEditSplitIn = QtGui.QPlainTextEdit(self.layoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEditSplitIn.setFont(font)
        self.textEditSplitIn.setObjectName("textEditSplitIn")
        self.verticalLayout_3.addWidget(self.textEditSplitIn)
        self.layoutWidget_10 = QtGui.QWidget(self.splitter_2)
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget_10)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_10 = QtGui.QLabel(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.textEditSplitOut1 = QtGui.QPlainTextEdit(self.layoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEditSplitOut1.setFont(font)
        self.textEditSplitOut1.setObjectName("textEditSplitOut1")
        self.verticalLayout_5.addWidget(self.textEditSplitOut1)
        self.layoutWidget_11 = QtGui.QWidget(self.splitter_2)
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_11)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_11 = QtGui.QLabel(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.textEditSplitOut2 = QtGui.QPlainTextEdit(self.layoutWidget_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEditSplitOut2.setFont(font)
        self.textEditSplitOut2.setObjectName("textEditSplitOut2")
        self.verticalLayout_4.addWidget(self.textEditSplitOut2)
        self.verticalLayout_6.addWidget(self.splitter_2)
        self.tabs.addTab(self.tabSplit, "")
        self.gridLayout_2.addWidget(self.tabs, 2, 0, 1, 1)
        self.pushButtonLaunch = QtGui.QPushButton(self.centralwidget)
        self.pushButtonLaunch.setObjectName("pushButtonLaunch")
        self.gridLayout_2.addWidget(self.pushButtonLaunch, 3, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButtonCopy = QtGui.QPushButton(self.centralwidget)
        self.pushButtonCopy.setObjectName("pushButtonCopy")
        self.horizontalLayout.addWidget(self.pushButtonCopy)
        self.pushButtonOverwrite = QtGui.QPushButton(self.centralwidget)
        self.pushButtonOverwrite.setObjectName("pushButtonOverwrite")
        self.horizontalLayout.addWidget(self.pushButtonOverwrite)
        self.gridLayout_2.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "DecalST", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFormat.setText(QtGui.QApplication.translate("MainWindow", "Format", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPath.setText(QtGui.QApplication.translate("MainWindow", "Fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonBrowseShiftIn.setText(QtGui.QApplication.translate("MainWindow", "Parcourir ...", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonShift.setText(QtGui.QApplication.translate("MainWindow", "Décallage de", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonBeginAt.setText(QtGui.QApplication.translate("MainWindow", "Début à", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSignShift.setItemText(0, QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSignShift.setItemText(1, QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "h", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "ms", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tabShift), QtGui.QApplication.translate("MainWindow", "Décallage", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPath_2.setText(QtGui.QApplication.translate("MainWindow", "Fichier 1", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonBrowseConcatIn1.setText(QtGui.QApplication.translate("MainWindow", "Parcourir ...", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPath_7.setText(QtGui.QApplication.translate("MainWindow", "Fichier 2", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonBrowseConcatIn2.setText(QtGui.QApplication.translate("MainWindow", "Parcourir ...", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPath_3.setText(QtGui.QApplication.translate("MainWindow", "Fichier de sortie", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonBrowseConcatOut.setText(QtGui.QApplication.translate("MainWindow", "Parcourir ...", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSignConcat.setItemText(0, QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSignConcat.setItemText(1, QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "h", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "ms", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Fichier 1 :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Fichier 2 :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Fichier de sortie :", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tabConcat), QtGui.QApplication.translate("MainWindow", "Concaténer", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPath_6.setText(QtGui.QApplication.translate("MainWindow", "Fichier original", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonBrowseSplitIn.setText(QtGui.QApplication.translate("MainWindow", "Parcourir ...", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPath_5.setText(QtGui.QApplication.translate("MainWindow", "Fichier 1", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonBrowseSplitOut1.setText(QtGui.QApplication.translate("MainWindow", "Parcourir ...", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPath_4.setText(QtGui.QApplication.translate("MainWindow", "Fichier 2", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonBrowseSplitOut2.setText(QtGui.QApplication.translate("MainWindow", "Parcourir ...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Fin du CD1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "h", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "ms", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Fichier de départ :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Fichier de sortie 1 :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Fichier de sortie 2 :", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.tabSplit), QtGui.QApplication.translate("MainWindow", "Splitter", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonLaunch.setText(QtGui.QApplication.translate("MainWindow", "Lancer !", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCopy.setText(QtGui.QApplication.translate("MainWindow", "Tout copier", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOverwrite.setToolTip(QtGui.QApplication.translate("MainWindow", "Cette action écrasera le fichier original par ce contenu", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOverwrite.setText(QtGui.QApplication.translate("MainWindow", "Écraser le(s) fichier(s) par ce contenu", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

